# Ejecucion de los test con el contenedor base 3.8-slim
name: test-code
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute test
        run: docker run -t -v `pwd`:/app/test jantoniovr/iv-2021-2022:3.8-slim